artifact_uri: ../mazda/mlflow_experiment/2/9d71c4081e5e48db8f0b607aa16d3fd6/artifacts
end_time: 1667289043471
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
run_id: 9d71c4081e5e48db8f0b607aa16d3fd6
run_name: rebellious-carp-306
run_uuid: 9d71c4081e5e48db8f0b607aa16d3fd6
source_name: ''
source_type: 4
source_version: ''
start_time: 1667288929628
status: 3
tags: []
user_id: naoto
