artifact_uri: ../mazda/mlflow_experiment/1/dcf5ab36f6a3455fb9a8453b81b417e8/artifacts
end_time: 1666972469789
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: dcf5ab36f6a3455fb9a8453b81b417e8
run_name: resilient-crane-886
run_uuid: dcf5ab36f6a3455fb9a8453b81b417e8
source_name: ''
source_type: 4
source_version: ''
start_time: 1666972255903
status: 3
tags: []
user_id: naotonaka
