artifact_uri: ../mazda/mlflow_experiment/1/e5c4f0157ae2477eaa948fa6d6fc4495/artifacts
end_time: 1667322301874
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: e5c4f0157ae2477eaa948fa6d6fc4495
run_name: masked-shrew-808
run_uuid: e5c4f0157ae2477eaa948fa6d6fc4495
source_name: ''
source_type: 4
source_version: ''
start_time: 1667315157849
status: 3
tags: []
user_id: naoto
