artifact_uri: ../mazda/mlflow_experiment/1/9c9360f00b0340969df0cf8c7507fed6/artifacts
end_time: 1667054076533
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 9c9360f00b0340969df0cf8c7507fed6
run_name: smiling-jay-844
run_uuid: 9c9360f00b0340969df0cf8c7507fed6
source_name: ''
source_type: 4
source_version: ''
start_time: 1667053822006
status: 3
tags: []
user_id: naotonaka
