artifact_uri: ../mazda/mlflow_experiment/2/e6a51054dbc144998bf8486f423d504a/artifacts
end_time: 1667289333052
entry_point_name: ''
experiment_id: '2'
lifecycle_stage: active
run_id: e6a51054dbc144998bf8486f423d504a
run_name: selective-boar-228
run_uuid: e6a51054dbc144998bf8486f423d504a
source_name: ''
source_type: 4
source_version: ''
start_time: 1667289106612
status: 3
tags: []
user_id: naoto
