artifact_uri: ../mazda/mlflow_experiment/1/8a0d3de2c31640b68943bfce63137057/artifacts
end_time: 1666963337681
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 8a0d3de2c31640b68943bfce63137057
run_name: carefree-bee-257
run_uuid: 8a0d3de2c31640b68943bfce63137057
source_name: ''
source_type: 4
source_version: ''
start_time: 1666959273525
status: 3
tags: []
user_id: naotonaka
