artifact_uri: ../mazda/mlflow_experiment/1/f46c067ca07641d9b63256de01ba80c5/artifacts
end_time: 1666972724349
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: f46c067ca07641d9b63256de01ba80c5
run_name: gentle-whale-529
run_uuid: f46c067ca07641d9b63256de01ba80c5
source_name: ''
source_type: 4
source_version: ''
start_time: 1666972555218
status: 3
tags: []
user_id: naotonaka
