artifact_uri: ../mazda/mlflow_experiment/1/acfae9b5a32642b29fa1ce95f81b9e03/artifacts
end_time: 1666973493973
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: acfae9b5a32642b29fa1ce95f81b9e03
run_name: big-roo-541
run_uuid: acfae9b5a32642b29fa1ce95f81b9e03
source_name: ''
source_type: 4
source_version: ''
start_time: 1666973259245
status: 3
tags: []
user_id: naotonaka
