artifact_uri: ../mazda/mlflow_experiment/1/5303a94c13524781abda5d95b1ccc94a/artifacts
end_time: 1667363680611
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 5303a94c13524781abda5d95b1ccc94a
run_name: incongruous-croc-32
run_uuid: 5303a94c13524781abda5d95b1ccc94a
source_name: ''
source_type: 4
source_version: ''
start_time: 1667355418909
status: 3
tags: []
user_id: naoto
