artifact_uri: ../mazda/mlflow_experiment/1/9b12cda8e65c4a478d2bfbb53e6dbc5e/artifacts
end_time: 1666959161610
entry_point_name: ''
experiment_id: '1'
lifecycle_stage: active
run_id: 9b12cda8e65c4a478d2bfbb53e6dbc5e
run_name: popular-stoat-66
run_uuid: 9b12cda8e65c4a478d2bfbb53e6dbc5e
source_name: ''
source_type: 4
source_version: ''
start_time: 1666959157521
status: 3
tags: []
user_id: naotonaka
